# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies, skip prepare scripts to control build explicitly
RUN npm install --ignore-scripts

# Copy source files
COPY src ./src
COPY debug.mjs ./
COPY test-server.mjs ./

# Build the project
RUN npm run build

# Expose any necessary port if needed (MCP works over stdio, so not required)

# Set the entrypoint command
CMD [ "node", "build/src/index.js" ]
